// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Circle: typeof import('./src/components/Circle.vue')['default']
    DayEchart: typeof import('./src/components/dayEchart.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftAnimation: typeof import('./src/components/leftAnimation.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Process: typeof import('./src/components/process.vue')['default']
    QuestionBoard: typeof import('./src/components/QuestionBoard.vue')['default']
    RightAnimation: typeof import('./src/components/rightAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/Slide.vue')['default']
    TimeDiff: typeof import('./src/components/timeDiff.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
  }
}
